### ISSUE TITLE
Mc crashes and idk why, halp plz

### ISSUE THREAD

**Issue by sbot50** [KabanFriends/LessUtilities#4]
Minecraft:
Version: 1.18.1
Loader: Default
Client: fabric loader 0.13.1 1.18.1

Mod List:
clientcommands v2.6 (mostly for the /ccalc command, its so useful)
cloth config v6.1.48
fabric API v0.46.6
LessUtilities v1.3.2
modmenu v3.0.1
optifabric v1.12.10
optifine 1.18.1 HD U H5

Crash Report:
[crash-2022-03-22_20.34.30-client.txt](https://github.com/KabanFriends/LessUtilities/files/8327386/crash-2022-03-22_20.34.30-client.txt)

If you need any other info just msg me.

**Comment by KabanFriends** [comment]
![image](https://user-images.githubusercontent.com/45000995/159562844-9ae7fe67-5a47-4819-a90e-6a691a1030bd.png)
use 1.18.2

**Comment by GeorgeRNG** [comment]
If cloth api is required maybe mention it in the readme
